[package]
name = "pixelflut"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
flume = "0.11.1"
image = "0.25.5"
thiserror = "2.0.9"
tokio = { version = "1.42.0", features = ["full"] }
