[package]
name = "pixelflut"
version = "0.1.0"
edition = "2021"

[features]
image = ["dep:image"]

[dependencies]
async-channel = "2.3.1"
thiserror = "2.0.9"
tokio = { version = "1", features = ["full"] }

image = { version = "0.25.5", optional = true }
